apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: privilege-escalation-pod
  name: privilege-escalation-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox
    name: privilege-escalation-pod
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
