apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: run-as-root-pod
  name: run-as-root-pod
spec:
  # securityContext:
  #   runAsUser: 1000
  #   runAsGroup: 3000
  #   fsGroup: 2000
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox
    name: run-as-root-pod
    resources: {}
    # securityContext:
    #   runAsNonRoot: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
