apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: run-as-non-root-pod
  name: run-as-non-root-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox
    name: run-as-non-root-pod
    resources: {}
    securityContext:
      runAsNonRoot: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
